// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.Data;

namespace TMS.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211228145038_EditData_Migration")]
    partial class EditData_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TMS.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("FeesPerDay")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("tblEmployees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            FeesPerDay = 15.0,
                            Name = "Employee 1"
                        },
                        new
                        {
                            EmployeeId = 2,
                            FeesPerDay = 25.0,
                            Name = "Employee 2"
                        },
                        new
                        {
                            EmployeeId = 3,
                            FeesPerDay = 10.0,
                            Name = "Employee 3"
                        });
                });

            modelBuilder.Entity("TMS.Models.EmployeeProject", b =>
                {
                    b.Property<int>("EmployeeProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("EmployeeProjectId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("tblEmployeesProjects");

                    b.HasData(
                        new
                        {
                            EmployeeProjectId = 1,
                            EmployeeId = 1,
                            EndDate = new DateTime(2021, 12, 26, 16, 50, 38, 308, DateTimeKind.Local).AddTicks(1972),
                            ProjectId = 1,
                            StartDate = new DateTime(2021, 12, 21, 16, 50, 38, 303, DateTimeKind.Local).AddTicks(8485),
                            Status = 2
                        },
                        new
                        {
                            EmployeeProjectId = 2,
                            EmployeeId = 2,
                            EndDate = new DateTime(2021, 12, 30, 16, 50, 38, 308, DateTimeKind.Local).AddTicks(4979),
                            ProjectId = 2,
                            StartDate = new DateTime(2021, 12, 23, 16, 50, 38, 308, DateTimeKind.Local).AddTicks(4963),
                            Status = 1
                        },
                        new
                        {
                            EmployeeProjectId = 3,
                            EmployeeId = 3,
                            EndDate = new DateTime(2022, 1, 4, 16, 50, 38, 308, DateTimeKind.Local).AddTicks(4986),
                            ProjectId = 3,
                            StartDate = new DateTime(2021, 12, 30, 16, 50, 38, 308, DateTimeKind.Local).AddTicks(4983),
                            Status = 0
                        },
                        new
                        {
                            EmployeeProjectId = 4,
                            EmployeeId = 2,
                            EndDate = new DateTime(2021, 12, 26, 16, 50, 38, 308, DateTimeKind.Local).AddTicks(4992),
                            ProjectId = 1,
                            StartDate = new DateTime(2021, 12, 18, 16, 50, 38, 308, DateTimeKind.Local).AddTicks(4989),
                            Status = 1
                        },
                        new
                        {
                            EmployeeProjectId = 5,
                            EmployeeId = 1,
                            EndDate = new DateTime(2021, 12, 29, 16, 50, 38, 308, DateTimeKind.Local).AddTicks(4998),
                            ProjectId = 3,
                            StartDate = new DateTime(2021, 12, 24, 16, 50, 38, 308, DateTimeKind.Local).AddTicks(4995),
                            Status = 2
                        });
                });

            modelBuilder.Entity("TMS.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.ToTable("tblProjects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            Name = "Project 1",
                            Size = 0
                        },
                        new
                        {
                            ProjectId = 2,
                            Name = "Project 2",
                            Size = 2
                        },
                        new
                        {
                            ProjectId = 3,
                            Name = "Project 3",
                            Size = 1
                        });
                });

            modelBuilder.Entity("TMS.Models.EmployeeProject", b =>
                {
                    b.HasOne("TMS.Models.Employee", "Employee")
                        .WithMany("Employeeprojects")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMS.Models.Project", "Project")
                        .WithMany("Employeeprojects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TMS.Models.Employee", b =>
                {
                    b.Navigation("Employeeprojects");
                });

            modelBuilder.Entity("TMS.Models.Project", b =>
                {
                    b.Navigation("Employeeprojects");
                });
#pragma warning restore 612, 618
        }
    }
}
